### PR TITLE
Added cases

### PR DESCRIPTION
**Pull request by Muxutruk2**

### CODE REVIEW

**Comment by Muxutruk2** [comment]
I know it is not as simple but its efficient

**Comment by Muxutruk2** [comment]
Wait you changed to "asala"

**Comment by Muxutruk2** [comment]
Edit it please

**Comment by robiot** [comment]
yes

**Comment by robiot** [comment]
i will merge when I don't feel confused anymore (i get confused by grammar)

**Comment by robiot** [comment]
basque grammar so hard.
it will make me not understand the language

**Pull request closed without merging**
